### ISSUE TITLE
Answer to the second question of Chapter 14 in Try_It_Yourself

### ISSUE THREAD

**Issue by DavidSwagger** [anthonydb/practical-sql-2#25]
Hi Anthony,

I have a question about the answer you gave to the second question of the Chapter 14 in Try_It_Yourself.

```
-- 2. Using any one of the presidents' speeches, count the number of
-- unique words that are five characters or more. Hint: you can use
-- regexp_split_to_table() in a subquery to create a table of words to count.
-- Bonus: remove commas and periods at the end of each word.

WITH
    word_list (word)
AS
    (
        SELECT regexp_split_to_table(speech_text, '\s') AS word
        FROM president_speeches
        WHERE speech_date = '1946-01-21'
    )

SELECT lower(
               replace(replace(replace(word, ',', ''), '.', ''), ':', '')
             ) AS cleaned_word,
       count(*)
FROM word_list
WHERE length(word) >= 5
GROUP BY cleaned_word
ORDER BY count(*) DESC;
```
The question and the answer you gave is shown above. In your anser, you are using 

```
WHERE length(word) >= 5
```
to filter unique words that are five characters or more. But I'm guessing we need to use

```
WHERE length(replace(replace(replace(word, ',', ''), '.', ''), ':', '')) >= 5
```
, right? Otherwise, you'll get several words that are 4 characters in your results.

**Comment by anthonydb** [comment]
You are correct, and thank you for pointing that out. You get this month's Eagle Eye award!

Rather than use `replace()` in the `WHERE` clause, I've moved the function into the Common Table Expression portion of the query to handle the issue. See https://github.com/anthonydb/practical-sql-2/commit/712cec0d31352e4d5e617da7c8f880fcefb60c28

The revised code is here, and I've given you thanks in the comment. Thanks!
https://github.com/anthonydb/practical-sql-2/blob/main/Try_It_Yourself/Try_It_Yourself.sql#L897

**Comment by DavidSwagger** [comment]
@anthonydb Thanks. My pleasure :)
