### ISSUE TITLE
Chapter 14: Mining Text to Find Meaningful Data

### ISSUE THREAD

**Issue by haochengxia** [anthonydb/practical-sql-2#6]
### General

| Item | Info |
|--|--|
| OS | Windows 11 22H2|
| pgAdmin4 | Version 6.19 |
| pgsql | PostgreSQL 15.2, compiled by Visual C++ build 1914, 64-bit|

### Issue or Question

**Chapter, page and code listing number:**

Thank you for writing such an informative book and providing a comprehensive set of guidelines. I have two small questions about the code examples.

#### Question 1

Chapter 14 - Pages 253, etc, Listing 14-12 (also involve other codes that contain `\n`)
```sql
UPDATE crime_reports
SET date_1 = 
(
    (regexp_match(original_text, '\d{1,2}\/\d{1,2}\/\d{2}'))[1]
        || ' ' ||
    (regexp_match(original_text, '\/\d{2}\n(\d{4})'))[1] 
        ||' US/Eastern'
)::timestamptz
RETURNING crime_id, date_1, original_text;
```

**Describe the issue or your question:**

`regexp_match(original_text, '\/\d{2}\n(\d{4})')` return `null`

**Reason:** The problem is caused by Windows 11, and it can work well when I change it to `regexp_match(original_text, '\/\d{2}\r\n(\d{4})')`. (adding `\r` before `\n`)

Here are the shortcuts.

![image](https://user-images.githubusercontent.com/44400703/234852124-1f52ba60-5171-4aec-b71e-bd2093b94eca.png)

![image](https://user-images.githubusercontent.com/44400703/234852185-918ee061-1f96-4994-a1d0-c900cc3e76c6.png)

#### Question 2

Chapter 14 - Listing 14-22 (also involve other codes that invoke `ts_headline()`)

```sql
SELECT president,
       speech_date,
       ts_headline(speech_text, to_tsquery('english', 'tax'),
                   'StartSel = <,
                    StopSel = >,
                    MinWords=5,
                    MaxWords=7,
                    MaxFragments=1')
FROM president_speeches
WHERE search_speech_text @@ to_tsquery('english', 'tax')
ORDER BY speech_date;
```

**Describe the issue or your question:**

If I do not add `'english'` as the first parameter, the result of `ts_headline()` will be abnormal.

**Reason**: without the first parameter, this function does not work as expected in my environment. When I add the first parameter, it works well, i.e., ` ts_headline('english', speech_text, to_tsquery('english', 'tax'), ...`.

Here are the shortcuts.

![image](https://user-images.githubusercontent.com/44400703/234865688-6eb334e3-9491-41bd-8302-23198ce5b2f4.png)

![image](https://user-images.githubusercontent.com/44400703/234865821-c9c17617-ef5e-4922-86f5-0774155980c6.png)

I'm not sure if it only happens on my computer.

**Comment by anthonydb** [comment]
Hello, @haochengxia! Thank you for reading Practical SQL and thank you for posting all the details of the issues you are experiencing. Let me address them one at a time:

**Listing 14-12**

I downloaded a fresh copy of the file `crime_reports.csv` and loaded it into a new `crime_reports` table. When I run the code in Listing 14-12, I see this result:

<img width="513" alt="Screenshot 2023-05-01 212310" src="https://user-images.githubusercontent.com/273891/235559913-06fdecb6-ed01-4602-9da3-6addd733ae6f.png">

It appears to be working as intended on my system. I'm not sure why you are receiving a different result.

A couple of ideas:

* By any chance, did you open the `crime_reports.csv` file in a spreadsheet or other program before importing it? Doing so can sometimes introduce additional line return or other hidden characters. You might want to try a fresh download and see if you obtain the same result.

* The only other guess is if something related to the default locale on your system causes this. I will have to investigate.

**Listing 14-22**

Yes, you must include the parameter of `'english'` in the `ts_headline()` function for it to work as intended. The reason is that in Listing 14-19, when we UPDATE the `search_speech_text` column to values of type `tsvector`, we specify the English language for the conversion:

```
UPDATE president_speeches
SET search_speech_text = to_tsvector('english', speech_text);
```

Thus, subsequently, we must specify English in order for the full-text functions to work properly. 

I hope this is helpful; please let me know how it goes and if you have other questions!

**Comment by haochengxia** [comment]
Thanks for your detailed and helpful answer! 
For question 1, as you pointed out, it happens after I open it with Excel. The code works well on a fresh copy of the file `crime_reports.csv`. For question 2, I further read the [documentation](https://www.postgresql.org/docs/current/textsearch-controls.html) of pgSQL.   

All of my questions have been resolved. However, I'm unsure if I overlooked any instructions regarding the usage of ts_headline() for solving question 2 in the book. If there aren't any relevant instructions, could it be mentioned in the [FAQ](https://github.com/anthonydb/practical-sql-2/blob/main/faq-updates-errata.md)? Thank you sincerely.
